### ISSUE TITLE
How to work with timezones?

### ISSUE THREAD

**Issue by TheRatG** [spatie/opening-hours#10]
Hello.

For example, I would like init open hours in UTC and need check isOpen() in America/Denver zone.

**Comment by sebastiandedeyne** [comment]
You could create a `DateTime` object with the current time, set the timezone to UTC and pass it into the `isOpenAt()` method.

https://github.com/spatie/opening-hours/blob/master/src/OpeningHours.php#L97

**Comment by sebastiandedeyne** [comment]
I'd accept a PR (with tests), that allows you to declare a timezone when creating the `OpeningHours` object, and does the conversion inside any method that uses a `DateTime` parameter.

**Comment by TheRatG** [comment]
Thanks a lot.

**Comment by sebastiandedeyne** [comment]
PR has been merged, and tagged as 1.1.0! 🎈
