### ISSUE TITLE
Non-composer installation?

### ISSUE THREAD

**Issue by adambundy** [spatie/opening-hours#102]
Thanks in advance for any help. Would it be possible to explain or add directions for installing this on a PHP site without using composer?

**Comment by kylekatarnls** [comment]
First of all, composer is the very standard way to require packages in composer and it optimizes for you the autoloading of classes, there is no good reason not to use it.

As spatie/opening-hours has no dependencies, you just need the `src` directory and a PSR-4 compliant autoloader:
https://www.php-fig.org/psr/psr-4/
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md
