### ISSUE TITLE
Import structured data

### ISSUE THREAD

**Issue by dsentker** [spatie/opening-hours#109]
As noted, the method asStructuredData()  converts a JSON-like data for plain text representation. It would be nice to import these rules which acts as a counterpart to create(), e.g.

```php
$openingHours = OpeningHours::fromStructuredData($jsonString);
assert($jsonString === $openingHours->asStructuredData());
```

**Comment by kylekatarnls** [comment]
Hi, what would be the difference with:
```php
OpeningHours::create(json_decode($jsonString));
```

**Comment by kylekatarnls** [comment]
Also, I'm not sure to understand as `asStructuredData` return an array and not a JSON string. In fact right now, as far as I know opening-hours has no feature related to JSON, so I would be tempted to let the responsibility of such parsing/formatting to the user using dedicated methods (e.g. `json_encode`/`json_decode`).

**Comment by dsentker** [comment]
Yes, i was wrong, ->asStructuredData() returns an array and not a string. Nevertheless, it would be great if there could be an import mechanism parallel to the export method (asStructuredData / fromStructuredData).

**Comment by kylekatarnls** [comment]
I do not wish to create method aliases. If it is not different from `create`, it will just add 2 ways of doing the same thing. If it's different please detail the input/output and I will re-open.
