### ISSUE TITLE
Quick Check?

### ISSUE THREAD

**Issue by sunscreem** [spatie/opening-hours#11]
I already love this package - thank you for publishing it. I've a project that can use it launching this week. This is all 100% working for me and I appreciate you probably don't have time to check over other people's code, but I wanted to quickly check with you if I'm using it right (ahead of you publishing the introduction blog post).

This is a small helper function I've written (laravel). 

This shop only has one set of opening hours per day - hence the ugly `$today[0]`:

```
public static function renderNextTenDaysOfTradingHoursHTML(){

        $openingHours = OpeningHours::create(config('site.tradingHours'));

        return collect()->range(0,10)->transform(function($day) use ($openingHours) {

            $today = $openingHours->forDate(Carbon::now()->addDay($day));

            if (count($today)) { return $today[0]->start()." - ".$today[0]->end(); }

            return "Closed";

        })->implode('<br>');

    }
```

I was little unsure how to check for the store being open/closed on a specific date using the `forDate` objects so I just ended up using a `count()`.

**Comment by sebastiandedeyne** [comment]
I actually reviewed this but forgot to reply heh.

Looks good to me! Thanks for submitting this, it's good to see actual usage so I know where to make improvements in future versions (e.g. the `$today[0]` bit isn't the nicest piece of code, but there's no other way at the moment).
