### ISSUE TITLE
Missing time zone information when exporting asStructuredData

### ISSUE THREAD

**Issue by jroedel** [spatie/opening-hours#121]
Hey guys, great work with this package!

I'm exporting structured opening hours data to a Place and I need the information of the timezone to be encoded. I'm creating the object using the `OpeningHours::create` static method with a time zone passed, but it appears that the timezone is never referenced elsewhere in the code.

Could we tack on the offset according to the [schema.org Time spec](https://schema.org/Time) if there's a timezone set?

**Comment by kylekatarnls** [comment]
Of course we should. Good point. I will check if there is already a way to do that or if we need to add some parameter.

**Comment by kylekatarnls** [comment]
Released in 2.4.0:
https://github.com/spatie/opening-hours#asstructureddatastrinf-format--hi-stringdatetimezone-timezone--array
