### ISSUE TITLE
Persist OpeningHours in DB

### ISSUE THREAD

**Issue by meyer59** [spatie/opening-hours#126]
Hi
Thanks for such a great package!
I was wondering how do you guy persist the OpeningHours in the DB ? I cannot find any models/query to do that.
Cordially

**Comment by atymic** [comment]
You could persist the array as JSON in the database, and load from there.

You'd still have to create an editor for users to edit the hours, however.

**Comment by meyer59** [comment]
How do you export/import the JSON with the package ? Any method ?

**Comment by atymic** [comment]
What do you mean? Just store the hours in the database, and then pass them to `OpeningHours::create()`

**Comment by kylekatarnls** [comment]
Hi, I first highly recommand to always store an atomic data in each DB field so having 1 DB row per range you could have columns for day, start hour, start minute, end hour, end minute then some foreign key to link it to a given business.

Avoid storing JSON in DB, it prevents from searching and sorting fast in data in it.

OpeningHours will not handle this part it's not up to the library as it depends on the app DB driver, relations etc. But in any case you will not store the object but the data array you used to create it.

**Comment by meyer59** [comment]
Got it, Thank you
