### ISSUE TITLE
nextOpen() returns wrong result if input array does not have slots in ascending order

### ISSUE THREAD

**Issue by jaysson** [spatie/opening-hours#128]
```php
$schedule = Carbon::now()->setDateTime(2019, 7, 6, 11, 29);

// Returns 2019-07-06 19:00:00
OpeningHours::createAndMergeOverlappingRanges(['saturday' => ['19:00-22:30','12:00-15:30']])->nextOpen($schedule);

// Returns 2019-07-06 12:00:00
OpeningHours::createAndMergeOverlappingRanges(['saturday' => ['12:00-15:30', '19:00-22:30']])->nextOpen($schedule);
```
May be the slots can be ordered while creating the `OpeningHours`?

**Comment by kylekatarnls** [comment]
I approve the idea.

Next version will allow unordered ranges:
https://github.com/spatie/opening-hours/pull/129

For the record, https://github.com/kylekatarnls/business-time allow you to enable opening hours globally on Carbon, so you can do: `Carbon::parse('2019-07-06 11:29')->nextOpen()` if you don't need multiple `OpeningHours` instances.
