### ISSUE TITLE
guardAgainstTimeRangeOverlaps not working as it should in version 1.9

### ISSUE THREAD

**Issue by joshuadegier** [spatie/opening-hours#134]
Hi,

I noticed the [guardAgainstTimeRangeOverlaps() in OpeningHoursForDay:161](https://github.com/spatie/opening-hours/blob/version-1.9/src/OpeningHoursForDay.php#L161) is not working as it should. For some reason it won't noticed dates overlapping when they are added in a particular order.

For example; the first line will throw the expected exception but the second wouldn't.

```
// Throws the error
OpeningHoursForDay::fromStrings(['08:00-18:00', '07:00-18:00']);

// Won't throw the error
OpeningHoursForDay::fromStrings(['07:00-18:00', '08:00-18:00']);
```

It all comes down to the method [containsTime() in TimeRange.php:77](https://github.com/spatie/opening-hours/blob/version-1.9/src/TimeRange.php#L77). The method in version 2 works fine by the way.

A simple modification that works (but probably isn't the most beautiful) is to check both "TimeRange 1 overlaps TimeRange2 [or] TimeRange2 overlaps TimeRange1". Which would result in the code below. 

```
    protected function guardAgainstTimeRangeOverlaps(array $openingHours)
    {
        foreach (Arr::createUniquePairs($openingHours) as $timeRanges) {
            if ($timeRanges[0]->overlaps($timeRanges[1]) || $timeRanges[1]->overlaps($timeRanges[0])) {
                throw OverlappingTimeRanges::forRanges($timeRanges[0], $timeRanges[1]);
            }
        }
    }
```

I tried the test suite in the current master branch as well, there are no issues there. It's a bug in version 1.x only.

**Comment by kylekatarnls** [comment]
Hi,

This would be a breaking change. Existing apps may start to throw the exception. I kindly invite you to upgrade to version 2 (the actively maintained version).

This can still be discussed, but as version 2 has the same minimum PHP compatibility, many more features and has your bug fixed, I see no relevant reason to spend efforts and risk BC in version 1.x.

Thanks.

**Comment by joshuadegier** [comment]
Hi Kyle,

point taken (and I've updated to v2 meanwhile). However I supposed people are more likely to not get an exception while expecting one instead of receiving one when they first didn't.

But I get your point.

Cheers.
