### ISSUE TITLE
Completing the ChangeLog between releases

### ISSUE THREAD

**Issue by rlweb** [spatie/opening-hours#138]
This really helps upgrade paths! Especially during releases between v1 and v2!

**Comment by kylekatarnls** [comment]
You can find them here: https://github.com/spatie/opening-hours/releases

I will copy them in the changelog.

**Comment by kylekatarnls** [comment]
Done.

**Comment by kylekatarnls** [comment]
I added some details about 2.x changes:
https://github.com/spatie/opening-hours/blob/master/CHANGELOG.md#200---2018-12-13
