### ISSUE TITLE
Use this library with eloquent model

### ISSUE THREAD

**Issue by hmunyeku** [spatie/opening-hours#147]
Dear
Is it possible to use your library with user eloquent model to know their availability?
How can I do that?
THanks

**Comment by kylekatarnls** [comment]
Hello, **opening-hours** relies on its data array. So you can easily store the whole data as a string in a column of your model using json_encode/serialize then restore it with json_decode/unserialize.

For a more structured approach (store more atomic data), if we omit the meta-data, you can simplify the structure for each business entity to:
```php
[
    $day => [$timeRange...],
    'exceptions' => [
        $date => [$timeRange...]
    ],
]
```
Each business entry -> N day definitions + N exceptions
1 day -> 1 name + N time ranges
1 exception -> 1 date (with or without year) + N time ranges
1 time range -> start hour (int) + start minute (int) + end hour (int) + end minute (int)

**Comment by musapinar** [comment]
> 1 time range -> start hour (int) + start minute (int) + end hour (int) + end minute (int)

@kylekatarnls why store as ```int``` instead of ```datetime``` ?

**Comment by kylekatarnls** [comment]
Datetime doest not fit as hour can be form 0 to 24 included, datetime has hour form 0 to 23 only. Then you would store useless date + second. Datetime is designed for a precise moment not recurrent time-only data, that's definitly not an appropriated type.

**Comment by san4io** [comment]
Hello, here you go:
Extend OpeningHours:
![image](https://user-images.githubusercontent.com/12079341/125793244-e6c95951-9e2c-46b8-ad43-aa6ffb0e970c.png)

Create json field in table, cast field as json and in your model create custom setters/getters:
![image](https://user-images.githubusercontent.com/12079341/125793386-d33eba84-8f31-450a-8366-2bbd53f5d4ed.png)
