### ISSUE TITLE
Method isOpenAt by only date returned false

### ISSUE THREAD

**Issue by KostiaBenner** [spatie/opening-hours#148]
When checking isOpenAt by date only, we get false, because the date is converted to datetime with a time equal to 00:00:00. I have open hours for this day from 08:00 to 20:00, I expect to get true, but I get false

```php
// Closed because it's after hours:
$openingHours->isOpenAt(new DateTime('2016-09-26 19:00:00')); // false

// Closed because Christmas was set as an exception
$openingHours->isOpenAt(new DateTime('2016-12-25')); // false
```
It would be cool to add a method for checking if a date is open without specifying the time

**Comment by kylekatarnls** [comment]
This exist has you can take the open hours for a given day with `->forDate()` and decide how to determine the day is open considering this hours. For instance, if you mean a day is open if it has at least 1 open time range, then use `->count()` on it.
```php
$openRangesCount = $openingHours->forDate(new DateTime('2016-12-25'))->count();

if ($openRangesCount ) {
  echo "$openRangesCount open hours ranges for 2016-12-25";
} else {
  echo "No open hours ranges for 2016-12-25";
}
```

Here is as a reusable function:
```php
function isDayOpen(\Spatie\OpeningHours\OpeningHours $openingHours, string $date): bool {
    return $openingHours->forDate(new DateTime($date))->count() > 0;
}

isDayOpen($openingHours, '2016-12-25');
isDayOpen($openingHours, '2020-09-03');
```

We have some special cases like the option `'overflow'` which allows 2016-12-24 open hours to be `20:00-03:00`, so it overflows to the night of 2016-12-25 and so 2016-12-25 00:00 is open while there may be no open ranges for this precise day.

Maybe some businesses will have at least 1 hour open every day and consider an open day is when the open time is more than an hour.

So I think it's fine to show explicitly in your code what is an open day for your business using the available tools.

Last note: `new DateTime('2016-12-25')` conversion to `new DateTime('2016-12-25 00:00:00')` is made by the native PHP `DateTime`, we don't have control over this conversion as it's done before opening-hours methods are called. And we can't know if time has been specified or not to create the instance when it's passed.

**Comment by kylekatarnls** [comment]
With the last release 2.9.0, it's now possible to pass a date string to `isOpenOn()`:

```php
$openingHours->isOpenOn('2016-12-25')
```

Consistently with the current behavior of `isOpenOn()` for day of week names, it ignores open hours overflowing from the previous day and will return `true` if there is at least 1 range starting on the given date.
