### ISSUE TITLE
isOpenOn timezone bug

### ISSUE THREAD

**Issue by ragingdave** [spatie/opening-hours#157]
When using isOpenOn, because you can't actually pass an object with a timezone attached or a time component in general, by default it will always be in server time but then would get the timezone of the hours applied, changing the date.

For example:
Server Timezone: UTC
Opening Hours Timezone: America/New_York

calling isOpenOn with any string date, will always check the previous day due to the timezone shifting

For example, during testing to see if this was a bug, using the date of 2020-10-12 results in the date to be checked as actually being 2020-10-11 20:00:00 due to the -4 hr timezone shift. I'm assuming this can happen as well for other timezones as well and potentially more severely.

**Comment by kylekatarnls** [comment]
Thanks for your help, it's now fixed in 2.9.1.

**Comment by MohmmedAshraf** [comment]
@kylekatarnls Hi, am working on a project which has places and those places have working hours, 
but some of the places for example working from (07:00 AM) to (02:00 AM) the next day and so on any idea how can i do this using this package?

**Comment by kylekatarnls** [comment]
As per the readme example, use `'overflow'​ => ​true​,`
