### ISSUE TITLE
Overlapping ranges with Data

### ISSUE THREAD

**Issue by MathieuMaas** [spatie/opening-hours#159]
Hi,
I want to add extra data to the overlapping ranges but they seem to keep throwing the follow error:
`Time ranges 09:00-21:00 and 20:00-23:00 overlap`

Is there any workaround for my specific case? The time ranges do not seem to merge correctly with the follow code:
```
$mergedRanges = \Spatie\OpeningHours\OpeningHours::mergeOverlappingRanges([ 
           'monday' => [
                ['hours' => '09:00-21:00', 'data' => 'test'],
                ['hours' => '20:00-23:00']
            ],
            'tuesday' => ['09:00-18:00'],
            'wednesday' => ['09:00-18:00'],
            'thursday' => ['09:00-18:00'],
            'friday' => ['09:00-18:00'],
            'saturday' => ['09:00-18:00'],
            'sunday' => [],
        ], []);
\Spatie\OpeningHours\OpeningHours::create($mergedRanges);

**Comment by kylekatarnls** [comment]
Hi, I think I see what can goes wrong. If we have 2 ranges with data to merge, we don't know how to merge the "data" part. Erase one of them keeping first/last, merge if array, concat if string? I can be done in many different ways but I don't think none would be obvious so it could lead to many unexpected behavior.

One may argue that we could smartly detect if there is only 1 "data" entries for multiple ranges to merge (still it would be heavy to implement) but it can still leads to inconsistency:

```
'monday' => [
  ['hours' => '03:00-10:00'],
  ['hours' => '07:00-12:00', 'data' => 'From sunrise to lunch'],
  ['hours' => '11:00-16:00'],
],
```
If we merge all an keep the "data" for the merged range it's no longer relevant:
```
'monday' => [
  ['hours' => '03:00-16:00', 'data' => 'From sunrise to lunch'],
],
```
Not true, not even close.

So I'm not sure we should support this kind of merge. So I recommend to pull all the data, merge pure ranges then determine how to re-apply data to new merged ranges according to your own business rules.

**Comment by MathieuMaas** [comment]
Yeah I get what you mean. The other issue I had was indeed the merging as you described . This does not to be working with the associative array. I don't know if this should be supported (Using just strings works fine). But this got me a bit of confused.
For example:
```
    $mergedRanges = \Spatie\OpeningHours\OpeningHours::mergeOverlappingRanges([
            'monday' => [
                ['hours' => '09:00-21:00'],
                ['hours' => '20:00-23:00']
            ],
            'tuesday' => [[' hours' => '09:00-18:00']],
        ]);
    \Spatie\OpeningHours\OpeningHours::create($mergedRanges);
```
Argument 1 passed to Spatie\OpeningHours\TimeRange::fromString() must be of the type string, array given, called in /vendor/spatie/opening-hours/src/OpeningHoursForDay.php on line 22

**Comment by kylekatarnls** [comment]
Yes, I know, that's what I mean by "pure ranges": turning `['hours' => '09:00-21:00']` into `'09:00-21:00'`. The associative keys `hours` and `data` are only there for the support of contextualized data actually introduced to provide a storage slot github.com/kylekatarnls/business-time needed, but `mergeOverlappingRanges` is a side util that know nothing about hours/data. 

Indeed the `overlap` message or the type hint errors are not very helpfull. I think `mergeOverlappingRanges` could actually "purify" the ranges.

**Comment by MathieuMaas** [comment]
Alright, I did solve this issue by merging the hours then adding the extra data after.

**Comment by kylekatarnls** [comment]
With the release [2.10.0](https://github.com/spatie/opening-hours/releases/tag/2.10.0) you no longer clean the array from its data/hours keys to merge them. `mergeOverlappingRanges` now cleanup all the "data" keys and simplify "hours" keys into simple arrays before processing.
