### ISSUE TITLE
getData question 

### ISSUE THREAD

**Issue by mjmarley** [spatie/opening-hours#166]
Hello,

I just stumbled across this amazing library after doing a very hacky solution myself. This is amazing. I also realized after the fact that I am using Ray also and have purchased 2 licenses for that as well a couple months ago. Small world I guess....

Anyways I am trying to figure out the best way to use getData on the "now" time regardless of where the current datetime sits in the array of my calendar. Is there a way to do that? Without knowing where in the array it is I can't figure out how. Here is my schedule. I need to have one command that will always return either "open", "emergency", or "emergency_weekend". And I guess the absence of one of those values would equal "closed". Does that make sense, or is there perhaps a better way to do this?

```php
$opening_hours = OpeningHours::create(
	array(
		'monday'     => array(
			array(
				'06:00-17:00',
				'data' => 'open',
			),
			array(
				'17:01-21:00',
				'data' => 'emergency',
			),
		),
		'tuesday'    => array(
			array(
				'06:00-17:00',
				'data' => 'open',
			),
			array(
				'17:01-21:00',
				'data' => 'emergency',
			),
		),
		'wednesday'  => array(
			array(
				'06:00-17:00',
				'data' => 'open',
			),
			array(
				'17:01-21:00',
				'data' => 'emergency',
			),
		),
		'thursday'   => array(
			array(
				'06:00-17:00',
				'data' => 'open',
			),
			array(
				'17:01-21:00',
				'data' => 'emergency',
			),
		),
		'friday'     => array(
			array(
				'06:00-17:00',
				'data' => 'open',
			),
			array(
				'17:01-21:00',
				'data' => 'emergency',
			),
		),
		'saturday'   => array(
			array(
				'07:00-21:00',
				'data' => 'emergency_weekend',
			),
		),
		'sunday'     => array(
			array(
				'07:00-21:00',
				'data' => 'emergency_weekend',
			),
		),
		'exceptions' => array(
			'2021-05-31' => array(
				'data' => 'holiday',
			),
			'01-01'      => array(
				'data' => 'holiday',
			),
			'12-24'      => array(
				'data' => 'holiday',
			),
			'12-25'      => array(
				'data' => 'holiday',
			),
		),
	),
	'America/Los_Angeles'
);
```

**Comment by mjmarley** [comment]
I think I figured it out:

ray ( $range = $opening_hours->currentOpenRange($now)->getData() );

**Comment by kylekatarnls** [comment]
Hello. Sorry I did not understand the question. Please:

- format the code in a readable way (indentation + php syntax highlight, see our README line 19: https://github.com/spatie/opening-hours/edit/master/README.md)
- show an example of input of the function/method and the expected output
- for a feature request, show the code you would imagine to use this feature
- for a bug, show the code you ran to get the issue and the actual behavior.

Don't involve any other library or app logic, use minimal code chunk we can run to reproduce. (For instance you can test your code on https://try-carbon.herokuapp.com/ to verify it's standalone).

**Comment by mjmarley** [comment]
Sorry about that. I edited the first post.  I am just trying to figure out a way to always return the data value based on the $now value obtained from: 

```
$now = new DateTime( 'now', new DateTimeZone( 'America/Los_Angeles' ) ); // production.
```
Based on the array in my first post it would either be open, emergency, emergency_weekend, or holiday. If none of those values are returned I would assume "closed". There must be a better way to do this than what I am currently doing, such as:

```
$scheduled = $opening_hours->isOpenAt( $now );
if ( true === $scheduled ) {
	$data = $opening_hours->currentOpenRange( $now )->getData();
}
```

This however doesn't get me the exceptions data value. Sorry if I am just missing something obvious, and thanks for any help you can provide.

**Comment by kylekatarnls** [comment]
The data can contains anything and status can only be open or close, so there is no real shortcut out of the box.

But `isOpenAt()` is a useless double check here as `currentOpenRange()` returning something means it's open. It would be a bit less explicit but a bit faster:

```php
function getStatus(DateTimeInterface $date): string
{
    $openRange = $opening_hours->currentOpenRange($date);

    return $openRange ? $openRange->getData() : 'closed';
}
```
