### ISSUE TITLE
Fatal error: Uncaught Spatie\OpeningHours\Exceptions\MaximumLimitExceeded:

### ISSUE THREAD

**Issue by JMultimidia** [spatie/opening-hours#169]
I registered in the database as default every day of the week with start and end time 00:00 and I get this error.

Fatal error: Uncaught Spatie\OpeningHours\Exceptions\MaximumLimitExceeded: No open date/time found in the next 8 days, use $openingHours->setDayLimit() to increase the limit. in /var/www/npopapp/mvc_painel/vendor/spatie/opening-hours/src/Exceptions/MaximumLimitExceeded.php:9 Stack trace: #0 /var/www/npopapp/mvc_painel/vendor/spatie/opening-hours/src/OpeningHours.php(390): Spatie\OpeningHours\Exceptions\MaximumLimitExceeded::forString('No open date/ti...') #1 /var/www/npopapp/mvc_painel/application/Controller/SiteController.php(363): Spatie\OpeningHours\OpeningHours->nextOpen(Object(Carbon\Carbon)) #2 /var/www/npopapp/mvc_painel/application/Core/Route.php(136): AgendaLabs\Controller\SiteController->deliverys(Array) #3 /var/www/npopapp/mvc_painel/application/Core/Route.php(84): AgendaLabs\Core\Route->run(Array, false) #4 /var/www/npopapp/public_html/index.php(65): AgendaLabs\Core\Route->get('deliverys', 'SiteController@...') #5 {main} thrown in /var/www/npopapp/mvc_painel/vendor/spatie/opening-hours/src/Exceptions/MaximumLimitExceeded.php on line 9

Code
foreach ($response['lojas'] as $loja) {		
				$horarios = $model->all('loja_horario', 'id', 'id_loja', $loja['id']);
					foreach ($horarios as $horario) {
					$ranges[$horario['dia']] =  [
						substr($horario['hora_inicio'], 0, 5) . "-" . substr($horario['hora_fim'], 0, 5),
						substr($horario['hora_inicio_02'], 0, 5) . "-" . substr($horario['hora_fim_02'], 0, 5),
					];
				}				
				$openingHours = OpeningHours::create($ranges);			
				$range = $openingHours->currentOpenRange($this->now);
					if ($range) {
						$loja['aberto'] = true;
						//$loja['desde'] = $range->start();
						$loja['fecha'] = $range->end();
					} else {
						$loja['aberto'] = null;
						$loja['abre'] = ucwords(Carbon::instance($openingHours->nextOpen($this->now))->isoFormat("ddd HH:mm"));
					}

**Comment by kylekatarnls** [comment]
Please provide your code in markdown tag and proper indent so I don't struggle to read and help:
<pre>
```php
if ($foo) {
    echo 'bar';
}
```
</pre>

Same for your expected output and to format stack trace of the error you get.

Thanks.
