### ISSUE TITLE
Can this library be used to match 2 groups of opening-hours?

### ISSUE THREAD

**Issue by TomasVotruba** [spatie/opening-hours#17]
Let's say we have teacher and student.

Teacher has some timetable (opening-hours) when he can teach,
and student has some timetable (opening-hours) when he can go to lectures.

**Does this library support matching these two?**

So I will see result: "*teacher 1* (9-11 AM) can teach *student 2* (9-10 AM) and *student 3* (10-11 AM)"

**Comment by sebastiandedeyne** [comment]
Currently not possible, comparing opening hours is outside of the scope of this package.

**Comment by TomasVotruba** [comment]
Thank you for the answer. Any recommnedation on package that might do that?

**Comment by sebastiandedeyne** [comment]
Hmm sorry not for that specific use case.

As a start, Carbon has some nice date comparison functions though: https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php#L1399

**Comment by TomasVotruba** [comment]
Cool. I'll check that package. 

Thanks for direction
