### ISSUE TITLE
exception ranges

### ISSUE THREAD

**Issue by ChrAus** [spatie/opening-hours#171]
Hi guys and congratulations to this amazing package.

Right now I am trying to store an exception range. Meaning the store is not opened for the next 2 weeks.
Is there an elegant way to do this?

Thanks in advance.

**Comment by kylekatarnls** [comment]
Hello 👋

Anything getting too custom can be handled with `'filters'`:

```php
$openingHours = OpeningHours::create([
    'monday' => [
       '09:00-12:00',
    ],
    'filters' => [
        function ($date) {
            if ($date->format('Y-m-d') >= '2021-06-14' && $date->format('Y-m-d') <= '2021-06-27') {
                return [];
            }
        },
    ],
]);
```

**Comment by ChrAus** [comment]
Thank you for the quick reply! Is there a chance to set a custom text for this exception and display it to the customer?

**Comment by kylekatarnls** [comment]
No, we can't scan the content of the closure to extract a human-friendly string that could match any custom function.

Simply use `DateTime::format` to display the date in English.

If you need to display dates in other languages or a more advance representation of periods of time, check out https://carbon.nesbot.com/
