### ISSUE TITLE
time first open

### ISSUE THREAD

**Issue by BartHuis** [spatie/opening-hours#18]
would be nice to have a function to get the timestamp of first next open time.
$openingHours->nextOpen(new DateTime('2016-09-26 19:00:00')); // returns dateobject of 2016-09-27 09:00:99

**Comment by freekmurze** [comment]
We'd accept a fully tested PR for that.

**Comment by Djuki** [comment]
@freekmurze Could you apply #hacktoberfest label to this feature request?

**Comment by sebastiandedeyne** [comment]
Added via spatie/opening-hours#21

**Comment by Djuki** [comment]
@sebastiandedeyne Thank you. It's never too late :)
