### ISSUE TITLE
Improve array shape phpdoc of create method

### ISSUE THREAD

**Issue by tyx** [spatie/opening-hours#183]
Hello !

First, thanks for this lib that make a wonderful job.

We just enable overflow through the `create` method but PHPStan is not really happy because according to the PHPDoc of this method, we cannot pass a boolean. And we don't have a dedicated method to enable overflow.

Will you accept a PR with an improvement of the php doc to follow PHPSTan array shape notation : https://phpstan.org/writing-php-code/phpdoc-types#array-shapes ?

**Comment by kylekatarnls** [comment]
Yes, sure!

Note that we still need to use the PHPDoc way (not the PHP 8 attribute-style) to declare array shape because we have PHP 7.0 in our compatibility range to support.

Thanks 🙏

**Comment by kylekatarnls** [comment]
Hello, can you try `composer require spatie/opening-hours:dev-feature/array-shape-create-phpdoc`?

**Comment by tyx** [comment]
Hello @kylekatarnls . Thank you for this ! It just miss `overflow` key apparently.

**Comment by kylekatarnls** [comment]
🤦‍♂️

**Comment by kylekatarnls** [comment]
Added.
