### ISSUE TITLE
Github URL update

### ISSUE THREAD

**Issue by dpi** [spatie/opening-hours#191]
Looks like the murze.be link https://murze.be/2016/10/managing-opening-hours-php/ on the Github project is no longer resolving

It looks like this is the new URL? https://freek.dev/595-managing-opening-hours-with-php

**Comment by kylekatarnls** [comment]
Thanks, indeed.

@freekmurze can you update the settings to change the website of the repository?

**Comment by freekmurze** [comment]
Done
