### ISSUE TITLE
[Question/Feature Request] How to get all days of the current week including days resulting from exceptions?

### ISSUE THREAD

**Issue by c33s** [spatie/opening-hours#192]
```php
$fakeNow = new Carbon('2010-10-11 14:00'); //monday
Carbon::setTestNow($fakeNow);
CarbonImmutable::setTestNow($fakeNow);

$openingHours = new OpeningHours();
$openingHours->fill([
    'monday'     => ['09:00-12:00'],
    'tuesday'    => ['09:00-12:00'],
    'exceptions' => [
        '2010-10-15' => ['09:00-12:00'], //friday
    ],
]);
$daysOpenThisWeek = $openingHours->forWeekWithExceptions();
```
the exception would mean that this week friday is also open. i am looking for a method similar to `forWeek` but with all days which result in being open because of exceptions. 

like `forWeekWithExceptions()`. which would return an array containing `monday`, `tuesday` and `friday` for the week starting with 2010-10-10 and return `monday` and `tuesday` normally.

do i miss something or doesn't such a feature exists?

**Comment by kylekatarnls** [comment]
The provided feature is `isOpenOn()` which tells you if a given date will be open at least once.

Which days you check and how you group them is up to you, just get whatever list of dates matters in your application context (next 3 days, current week, next week, all the month) and filter this list to keep only dates for which `isOpenOn()` return true. `CarbonPeriod` would be the ideal tool to provide the initial list of days and has `->filter()`.

Then as it returns a list of `Carbon` instance, it's also rather straightforward to get week day name of each.

```php
$fakeNow = new Carbon('2010-10-11 14:00'); //monday
Carbon::setTestNow($fakeNow);
CarbonImmutable::setTestNow($fakeNow);

$openingHours = new \Spatie\OpeningHours\OpeningHours();
$openingHours->fill([
    'monday'     => ['09:00-12:00'],
    'tuesday'    => ['09:00-12:00'],
    'exceptions' => [
        '2010-10-15' => ['09:00-12:00'], //friday
    ],
]);

$start = CarbonImmutable::now()->startOfWeek();

var_dump(iterator_to_array(
    $start->daysUntil($start->endOfWeek())
        ->filter(static fn (CarbonImmutable $date) => $openingHours->isOpenOn($date->format('Y-m-d')))
        ->map(static fn (CarbonImmutable $date) => $date->dayName)
));
```

Just a little more verbose if you didn't yet upgraded to PHP >= 8:
```php
var_dump(iterator_to_array($start->daysUntil($start->endOfWeek())->filter(static function (CarbonImmutable $date) use ($openingHours) {
    return $openingHours->isOpenOn($date->format('Y-m-d'));
})->map(static function (CarbonImmutable $date) {
    return $date->dayName;
})));
```

**Comment by c33s** [comment]
thanks you very much for the example. 

don't you think it would make sense to have this example code in this lib as function (`getOpenDays($from, $to)`)?

**Comment by kylekatarnls** [comment]
IMO, it's already too specific, depending on the application preferred output would the English name or the name translated for the current user, or the day number, but all those output would make sense only if from/to are week start and end, it's useless if your period is a whole month, so this method would more likely just return raw DateTime objects (not Carbon ones as spatie/opening-hours is also meant to be usable without installing Carbon), also if the list is big, it's interesting to keep the iterator instead of converting it into an array. So in the end if this method would be implemented in a generic way you wouldn't have less code to write.
