### ISSUE TITLE
GitHub repository link not working

### ISSUE THREAD

**Issue by winfried-van-loon** [spatie/opening-hours#206]
The repository is pointing to [freek.dev/2016/10/managing-opening-hours-php/](https://freek.dev/2016/10/managing-opening-hours-php/) but the page returns a 404 error.

**The specific link:**
> <img width="340" alt="Screenshot 2022-10-12 at 18 34 58" src="https://user-images.githubusercontent.com/756956/195399279-93dff553-c012-4160-895c-0486c78de2a4.png">

**The error page:**
> <img width="1153" alt="Screenshot 2022-10-12 at 18 36 24" src="https://user-images.githubusercontent.com/756956/195399518-e5857106-3c18-4793-bf03-582ed197ef1a.png">

**Suggestion:**
I think this could be a working link so the same or similar content:
https://freek.dev/595-managing-opening-hours-with-php

**Comment by kylekatarnls** [comment]
@freekmurze 🙏

**Comment by freekmurze** [comment]
Fixed 👍
