### ISSUE TITLE
Adding seconds precision to exceptions

### ISSUE THREAD

**Issue by vipera7** [spatie/opening-hours#240]
Hi,

Currently, exceptions are defined with a time range using hours and minutes. This feature request proposes an enhancement to include seconds precision. 

Instead of specifying exceptions like : 

```
'exceptions' => [
    '2016-11-11' => ['09:00-12:00'],
],

```
users should be able to define exceptions with seconds precision, such as : 

```
'exceptions' => [
    '2016-11-11' => ['09:00:54-12:00:21'],
],
```

This enhancement will provide more granularity and accuracy when specifying time ranges for exceptions, allowing for a more precise representation of time intervals.

**Comment by kylekatarnls** [comment]
Hello,

This could be investigated, however I feel it could introduce quite a lot of complexity and maintenance burden for a rare case. Most business just use minute granularity to describe opening hours.
