### ISSUE TITLE
next/previous open when "isAlwaysOpen" throws

### ISSUE THREAD

**Issue by BenMaldoner** [spatie/opening-hours#257]
Hi Spatie. We use the latest spatie/opening-hours version (4.0.2) and I wanted to know if the "nextOpen" and "previousOpen" functions should really throw an Exception when the opening hours are considered "isAlwaysOpen". E.g.:

```
      $openingHours = OpeningHours::create([
         'monday'     => ['00:00-24:00'],
         'tuesday'    => ['00:00-24:00'],
         'wednesday'  => ['00:00-24:00'],
         'thursday'   => ['00:00-24:00'],
         'friday'     => ['00:00-24:00'],
         'saturday'   => ['00:00-24:00'],
         'sunday'     => ['00:00-24:00'],
      ]);
      $from = new \DateTime("2024-10-27 20:59");
      $alwaysOpen = $openingHours->isAlwaysOpen($from); // true
      $previousOpen = $openingHours->previousOpen($from); 
      // throws Spatie\OpeningHours\Exceptions\MaximumLimitExceeded: No close date/time found in the previous 8 days, use $openingHours->setDayLimit() to increase the limit.
```
Wouldn't it make more sense to return "00:00" of the day after the day that was passed to the nextOpen function (or maybe even the same day)? And the day before in case of previousOpen?

**Comment by kylekatarnls** [comment]
Hello `nextOpen` returns the date-time of the next time that business state will switch from closed to open and `previousOpen` returns the date-time of the previous time that the business state switched from closed to open.

If the business state never change there is no date-time that correctly answer the question.

The method `isAlwaysOpen` is precisely there so you can anticipate such case and deal it according to your own business rules.

Exceptions are always safer than returning wrong or ambiguous results.

You can still catch them, then you know why the call was not safe and you can react appropriately to the reason.

**Comment by BenMaldoner** [comment]
Thanks for the explanation. Maybe it helps others if you put the info of your comment into the docs.

**Comment by kylekatarnls** [comment]
Done.
