### ISSUE TITLE
Suggestion: Adding remarks to exceptions

### ISSUE THREAD

**Issue by Sennik** [spatie/opening-hours#27]
Great package!

Idea: It would come handy to be able to use remarks on the exceptions:

```
$openingHours = OpeningHours::create([
    'monday' => ['09:00-12:00', '13:00-18:00'],
    'tuesday' => ['09:00-12:00', '13:00-18:00'],
    'wednesday' => ['09:00-12:00'],
    'thursday' => ['09:00-12:00', '13:00-18:00'],
    'friday' => ['09:00-12:00', '13:00-20:00'],
    'saturday' => ['09:00-12:00', '13:00-16:00'],
    'sunday' => [],
    'exceptions' => [
        '2016-12-25' => [
            'hours' => [],
            'remarks' => 'First christmas day closed'   
        ],
        '2016-12-26' => [
            'hours' => [],
            'remarks' => 'First christmas day closed'   
        ],
        '2011-01-01' => [
            'hours' => ['13:00-18:00'],
            'remarks' => 'Newyearsday opening times'   
        ]
    ],
]);
```

**Comment by sebastiandedeyne** [comment]
I'd accept a PR that adds this

**Comment by sebastiandedeyne** [comment]
Closing this as I'll be adding this in v2 together with #38

**Comment by Sennik** [comment]
Thanks! 

Another thing a ran into:

I have a shop that is open every last sunday of the month. Is it possible to add something for this? This kind of iterations are very common these days: Montly exceptions (With descriptions ofcourse ;-)).

$openingHours = OpeningHours::create([
    'monday' => ['09:00-12:00', '13:00-18:00'],
    'tuesday' => ['09:00-12:00', '13:00-18:00'],
    'wednesday' => ['09:00-12:00'],
    'thursday' => ['09:00-12:00', '13:00-18:00'],
    'friday' => ['09:00-12:00', '13:00-20:00'],
    'saturday' => ['09:00-12:00', '13:00-16:00'],
    'sunday' => [],
    'montly' => [
        'first' => [
        ],
        'second' => [
        ],
        'third' => [
        ],
        'fourth' => [
            'sunday' => [
                'hours' => ['10:00' => '17:00'],
                'remarks' => 'Open every last sunday of the month'   
            ],
        ],
    'exceptions' => [
        '2016-12-25' => [
            'hours' => [],
            'remarks' => 'First christmas day closed'   
        ],
        '2016-12-26' => [
            'hours' => [],
            'remarks' => 'First christmas day closed'   
        ],
        '2011-01-01' => [
            'hours' => ['13:00-18:00'],
            'remarks' => 'Newyearsday opening times'   
        ]
    ],
]);

**Comment by kylekatarnls** [comment]
Hi @Sennik your fourth sunday of each month is too specific, this would open doors to too many business-specific request. Instead we can consider having a closure system: you configure a function that get a date object then return the hours then code your own logic of how to calculate those hours inside the function, a bit similar to holiday closures in [cmixin/business-day](https://github.com/kylekatarnls/business-day) that allow to handle "third Monday of January" for the Martin Luther King Jr. Day: https://github.com/kylekatarnls/business-day/blob/master/src/Cmixin/Holidays/us-national.php#L6

But array definition for days meta data are now in the pipe for the version 2.

**Comment by kylekatarnls** [comment]
Hi all,

I added a filters system to handle exceptions such as *fourth Sunday*. It's not definitive but it should be (or something very close) in the version 2.0. You can yet test this feature, meta data and immutable dates support by requiring the `dev-filters` version (it's a temporary branch for test purpose only).

Your feedback on it is welcome. and you can also review code changes on (#83, #80 and #75)

Here is the documentation of those new features:

> You can add data in definitions then retrieve them:
> 
> ```php
> $openingHours = OpeningHours::create([
>     'monday' => [
>         'data' => 'Tipical monday',
>         '09:00-12:00',
>         '13:00-18:00',
>     ],
>     'tuesday' => [
>         '09:00-12:00',
>         '13:00-18:00',
>         [
>             '19:00-21:00',
>             'data' => 'Extra on Tuesday evening',
>         ],
>     ],
>     'exceptions' => [
>         '2016-12-25' => [
>             'data' => 'Closed for Christmas',
>         ],
>     ],
> ]);
> 
> echo $openingHours->forDay('monday')->getData(); // Tipical monday
> echo $openingHours->forDate(new DateTime('2016-12-25'))->getData(); // Closed for Christmas
> echo $openingHours->forDay('tuesday')[2]->getData(); // Extra on Tuesday evening
> ```
> 
> In the example above, data are string but it can be any kind of values. So you can embed multiple properties in an array.
> 
> For structure convenience, the data-hours couple can be a fully-associative array, so the example above is strictly equivalent to the following:
> 
> ```php
> $openingHours = OpeningHours::create([
>     'monday' => [
>         'hours' => [
>             '09:00-12:00',
>             '13:00-18:00',
>         ],
>         'data' => 'Tipical monday',
>     ],
>     'tuesday' => [
>         ['hours' => '09:00-12:00'],
>         ['hours' => '13:00-18:00'],
>         ['hours' => '19:00-21:00', 'data' => 'Extra on Tuesday evening'],
>     ],
>     'exceptions' => [
>         '2016-12-25' => [
>             'hours' => [], 
>             'data' => 'Closed for Christmas',
>         ],
>     ],
> ]);
> ```
> 
> The last structure tool is the filter, it allows you to pass closures (or callable function/method reference) that take a date as parameter and returns the settings for the given date.
> 
> ```php
> $openingHours = OpeningHours::create([
>     'monday' => [
>        '09:00-12:00',
>     ],
>     'filters' => [
>         function ($date) {
>             $year = intval($date->format('Y'));
>             $easterMonday = new DateTimeImmutable('2018-03-21 +'.(easter_days($year) + 1).'days');
>             if ($date->format('m-d') === $easterMonday->format('m-d')) {
>                 return []; // Closed on Easter monday
>                 // Any valid exception-array can be returned here (range of hours, with or without data) 
>             }
>             // Else the filter does not apply to te given date
>         },
>     ],
> ]);
> ```
> 
> If a callable is found in the `"exceptions"` property, it will be added automatically to filters so you can mix filters and exceptions both in the **exceptions** array. The first filter that returns a non-null value will have precedence over next filters and the **filters** array has precedence over the filters inside the **exceptions** array.
> 
> Warning: as we will loop on all filters for each date we need to retrieve opening hours and cannot neither predicate or cache the result (can be random function) you must be careful with filters, too many filters or long process inside filters can have a significant impact on the performance.
>

**Comment by kylekatarnls** [comment]
**2.0.0** released. 🕺
