### ISSUE TITLE
Add context to time ranges

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/opening-hours#34]
Time ranges should know their dates (or create a new value object that provides this)

**Comment by kylekatarnls** [comment]
Hi @sebastiandedeyne, I'm not sure time ranges should keep a link to their dates if they can work without it. Can you provide an example of situation where it is useful?

**Comment by sebastiandedeyne** [comment]
IIRC this was so you could format a time range and date in one go. This isn't important at all though, until someone actually needs it, I'd say hold off on this.
