### ISSUE TITLE
Use Carbon and use it instead of DateTime (or make it optional)

### ISSUE THREAD

**Issue by DeftNerd** [spatie/opening-hours#54]
I have code like 
`Carbon\Carbon::instance($openingHours->nextOpen(new DateTime()))->diffForHumans()`

I would love to set a variable in the `openingHours.php` config file like `'library' => 'Carbon',` or `'library' => 'DateTime',`

This could result in all calls that return dates or times to return Carbon objects that could then be formatted with the existing Carbon fluent commands.

`$openingHours->nextOpen()->diffForHumans()` could return the string `6 hours from now` and `$openingHours->nextOpen()->format('l@h:i A')` could return `Thursday@09:00 AM`

**Comment by sebastiandedeyne** [comment]
Gonna hold off on this for now. Not planning to add any configuration any time soon.

**Comment by kylekatarnls** [comment]
Hi, I made a Carbon mixin to use spatie/opening-hours directly on Carbon instances: https://github.com/kylekatarnls/business-time

**Comment by c33s** [comment]
again the request to switch to carbon or make it configurable. 

as carbon has the option to set the "now" date to a given date, it makes testing so much easier
```
$testDate = Carbon::create(2018, 6, 18, 12);
Carbon::setTestNow($testDate);
```

https://dev.to/nikoheikkila/quick-tip-faking-dates-in-php-with-carbon-2l9i

any chance to let this happen?

**Comment by kylekatarnls** [comment]
I made an experiment (not yet documented) and I still need to make some check before releasing it, but you can try to add this in the option to use Carbon or CarbonImmutable:

`'dateTimeClass' => CarbonImmutable::class,`

and run `composer require spatie/opening-hours:2@dev` to get the last changes in master branch.

**Comment by c33s** [comment]
@kylekatarnls i tried the cmixin package but it was quite cumbersome to use compared with using this lib directly.  i to a similar method you mentioned in your first comment.

i haven't had time to test your branch but i happily will try it as the possibility to set the used date class is, in my opinion, an even better approach. i hope i can test it in a week or two, as i am currently working on a different project.

thank you very much for your fast response. really awesome!
