### ISSUE TITLE
nextClose() just like nextOpen()

### ISSUE THREAD

**Issue by DeftNerd** [spatie/opening-hours#55]
This would be very clean and useful...
```
if($openingHours->isOpen()) {
  $closesAt = $openingHours->nextClose(new DateTime());
} else {
  $opensAt = $openingHours->nextOpen(new DateTime());
}
```

`$openingHours->nextOpen(new DateTime())` is a great way to output the next time a business opens, but there is not a correlary `nextClose()` command!

It would be very useful to calculate how long a business is going to be open for until it closes.

**Comment by sebastiandedeyne** [comment]
I'd accept a test PR that adds this.

**Comment by jerome2710** [comment]
#68

**Comment by miclf** [comment]
Now that #68 has been merged, I think this issue can be closed.
