### ISSUE TITLE
Feature suggestion: add/subtract business days

### ISSUE THREAD

**Issue by jkudish** [spatie/opening-hours#56]
Would love to have a `->addBizDays(15)` and `->subBizDays(3)` which add/subtract a certain number of business days. What do you think?

**Comment by jkudish** [comment]
Here's a really simple implementation, in case it helps anyone, this is using the `Illuminate\Support\Carbon` which supports macros:

```php
Carbon::macro('addBizDays', function($bizDaysToAdd){
            $day = $this;
            $openingHours = app(OpeningHours::class);
            for ($daysAdded = 0; $daysAdded < $bizDaysToAdd; $daysAdded++) {
                $day = $openingHours->nextOpen($day);
            }

            return $day;
        });
```

**Comment by sebastiandedeyne** [comment]
I think this is a bit too specific to add here, and the implementation is easily done in your own app.

If more people want this I'll reconsider, but gonna hold off for now.

**Comment by jkudish** [comment]
Fair enough; would be a nice to have for sure :)
