### ISSUE TITLE
Opening hours across Midnight

### ISSUE THREAD

**Issue by rabauss** [spatie/opening-hours#88]
Is there a way to define Opening Hours accross Midnight??

For example:
```
$openingHours = OpeningHours::create([
    'tuesday'     => ['09:00-00:00'],
    'tuesday'     => ['09:00-03:00'],
    'exceptions' => [
        '2019-02-05' => ['09:00-04:00'],
    ],
]);
```
If we split into two slots ``09:00-23-59`` and ``00:00-03:00``, then at 16:00 the ``nextClose`` would be ``23:59`` instead of ``03:00``. Has someone a possible solution for that problem?

**Comment by kylekatarnls** [comment]
Yep, explained here: #22, you can use `'09:00-24:00'`

**Comment by rabauss** [comment]
Unfortunately this won't bring the right solution for this:
````
$openingHours = OpeningHours::create([
    'monday'    => ['09:00-03:00'],
    'tuesday'   => ['09:00-03:00'],
]);
````
transformed to:
````
$openingHours = OpeningHours::create([
    'monday'     => ['09:00-24:00'],
    'tuesday'    => ['00:00-03:00','09:00-24:00'],
    'wednesday'  => ['00:00-03:00'],
]);
````

this won't say `nextClose` is ``03:00`` - it returns: ``2019-02-05 00:00:00.000000``

**Comment by kylekatarnls** [comment]
I don't think we should handle `['09:00-03:00']` but consecutive `24:00` to next `00:00` seems fair. I will try to find a way.

**Comment by kylekatarnls** [comment]
Fixed in #90, please try to update to `dev-master` and see if it fixes your problem. Thanks.

**Comment by kylekatarnls** [comment]
Released in https://github.com/spatie/opening-hours/releases/tag/2.1.0-beta.1

**Comment by rabauss** [comment]
Just, wanted to give short feedback: it's working!
thank you!!

The "``24:00`` Hack" should be added in the Readme ;-)

**Comment by kylekatarnls** [comment]
From the README:

> 'wednesday' => ['22:00-24:00'], // use the special "24:00" to reach midnight included

**Comment by gildebrand** [comment]
I'd like to express my interest as well for the possibility to have opening hours across midnight. Although it doesn't make sense technically, opening hours in the format of `12:00-02:00` is a format that's commonly used in real life (for restaurants, night clubs, etc.). I think this would be a great feature to have.

**Comment by kylekatarnls** [comment]
So specifications would be:

Instead of having an error if start > end, we would consider start-24:00 + 00:00-end (on the next day) but if I want to display those opening hours, I would still get start-end as in the definition.

Right?

This change may be considered as breaking because if an application rely on the verification to handle some user input opening hours validation, now it will no longer throw an exception and it may allow inputs the application itself would not be ready to handle.

So as long as we don't start a new major release, it must remain an option you first need to enable such as: `12:00-02:00+1day`, or `12:00-24+02:00`, those notations are ugly, but we need something to say explicitly we want the hour on the next day. Or else it can be a property at the root of the definition array: `'allow_overflow' => true` maybe.

I'm open to pull-requests for this.

**Comment by gildebrand** [comment]
I think the best way would be to pass a flag when creating the `OpeningHours` instance. Maybe as second argument of `OpeningHours::create`. The `12:00-24+02:00` option would also be viable I think, but passing a flag would be preferred.

I might have a look  at implementing this. If I find a good way to solve this, I'll submit a PR.

**Comment by kylekatarnls** [comment]
Explanation about flags pitfalls: https://github.com/spatie/opening-hours/pull/104#issuecomment-485422340

So final API is:
```php
$openingHours = \Spatie\OpeningHours\OpeningHours::create([
    'overflow' => true,
    'friday'   => ['20:00-03:00'],
    'saturday' => ['20:00-03:00'],
], null);
```

It will be released on 2.2.0.

Thank you to @rlweb for the implementation, thank you all for your feedback on this feature.

**Comment by rabauss** [comment]
Oh nice, that we can now directly create overflowing opening hours.

Recently we had some problems with exceptions and overflows. If you have closed on one day, then of course the overflow should also be closed, too. Or if you have special overflow opening then the overflow should not overwrite the regular opening hours on next day.

Here some example data:
```
$openingHours = \Spatie\OpeningHours\OpeningHours::create([
    'overflow' => true,
    'thursday'   => ['20:00-03:00'],
    'friday'   => ['20:00-03:00'],
    'saturday' => ['20:00-03:00'],
    'sunday' => [],

    'exceptions' => [
        '2019-05-10' => [
            'hours' => ['20:00-02:00'],
        ],
        '2019-05-11' => [
            'hours' => [],
        ],
    ],
]);
```

Tests should be:
```
$openingHours->isOpenAt(new DateTime('2019-05-10 02:00:00')); // true (from regular thursday)
$openingHours->isOpenAt(new DateTime('2019-05-11 01:00:00')); // true (from exception 2019-05-10)
$openingHours->isOpenAt(new DateTime('2019-05-12 02:00:00')); // false (from exception 2019-05-11)
```

Can the extension handle that? would be nice if it can ;-)
Maybe in the next few days I have some time to test it by myself.

**Comment by kylekatarnls** [comment]
Hello @rabauss I do not plan to add this myself right now and as 2.2.0 has been released, I encourage you to create a new issue for this new part of the feature. Maybe you could add your unit tests and submit them as a pull-request. I would merge them on a dedicated branch to the feature so it could help to implement it if someone is interested in proposing a solution for this.
