### ISSUE TITLE
Return a Period of days, based on a start DateTime

### ISSUE THREAD

**Issue by leroy0211** [spatie/opening-hours#94]
It would help a lot if this library would add a simple method to return a Period of n-days, based on a start DateTime. 
For example to return the 14 days from monday this week. 

Right now I'm using a little snippet to do this:

```php
$openingTimes = OpeningHours::create([...]);
$first = new \DateTimeImmutable('monday this week');
$range = new \DatePeriod($first, new \DateInterval('P1D'), $first->add(new \DateInterval('P14D')));

foreach ($range as $date) {
   $openingDay = $openingTimes->forDate($date);
   $keyedIndex = Day::onDateTime($date);
   ...
}

```

**Comment by kylekatarnls** [comment]
Date ranges is not related to opening hours. Carbon (https://carbon.nesbot.com/docs/#api-period) and many other libraries do the job. To be efficient, a library must focus a main purpose and rely on other libraries that suit better for other usages.

And as OpeningHours can be plugged in Carbon using [business-time](https://github.com/kylekatarnls/business-time), you can get the whole thing working nicely with a very clean code by installing: `composer require kylekatarnls/business-time` (this library is enough as it includes opening-hours and carbon).

```php
BusinessTime::enable(Carbon::class, [...]);

foreach (CarbonPeriod::create('monday this week', '1 day', 'monday this week + 14 days') as $date) {
  $openingDay = $date->getCurrentDayOpeningHours();
  $keyedIndex = $date->dayName;
}
```

Bonus: use `locale()` to translate `dayName` in any of the hundred locales supported by Carbon.
