### ISSUE TITLE
Can't use the data string because it's not set as a time?

### ISSUE THREAD

**Issue by edgren** [spatie/opening-hours#95]
Hi!

I ran up on a bug in your function. When I try the example below, I'll get this error message:

```Fatal error: Uncaught Spatie\OpeningHours\Exceptions\InvalidTimeRangeString: The string `Extra on Tuesday evening` isn't a valid time range string. A time string must be a formatted as `H:i-H:i`, e.g. `09:00-18:00`. in F:\Websites\www\erik-edgren-blog\vendor\spatie\opening-hours\src\Exceptions\InvalidTimeRangeString.php:9 Stack trace: #0 F:\Websites\www\erik-edgren-blog\vendor\spatie\opening-hours\src\TimeRange.php(31): Spatie\OpeningHours\Exceptions\InvalidTimeRangeString::forString('Extra on Tuesda...') #1 F:\Websites\www\erik-edgren-blog\vendor\spatie\opening-hours\src\TimeRange.php(58): Spatie\OpeningHours\TimeRange::fromString('Extra on Tuesda...') #2 F:\Websites\www\erik-edgren-blog\vendor\spatie\opening-hours\src\TimeRange.php(63): Spatie\OpeningHours\TimeRange::fromArray(Array) #3 F:\Websites\www\erik-edgren-blog\vendor\spatie\opening-hours\src\OpeningHoursForDay.php(35): Spatie\OpeningHours\TimeRange::fromDefinition(Array) #4 [internal function]: Spatie\OpeningHours\OpeningHoursForDay::Spatie\OpeningHours\{closur in F:\Websites\www\erik-edgren-blog\vendor\spatie\opening-hours\src\Exceptions\InvalidTimeRangeString.php on line 9```

```PHP
	$openingHours = Spatie\OpeningHours\OpeningHours::create([
		'monday' => [
			'data' => 'Typical Monday',
			'09:00-12:00',
			'13:00-18:00',
		],
		'tuesday' => [
			'09:00-12:00',
			'13:00-18:00',
			[
				'19:00-21:00',
				'data' => 'Extra on Tuesday evening',
			],
		],
		'exceptions' => [
			'2016-12-25' => [
				'data' => 'Closed for Christmas',
			],
		],
	]);
```

Please fix!

**Comment by kylekatarnls** [comment]
Fixed, patch will be released soon.

**Comment by kylekatarnls** [comment]
Please install `2.1.1` and retry. Thanks.
