### ISSUE TITLE
TimeRange array definition must at least contains an "hours" property.

### ISSUE THREAD

**Issue by gilsondelrei** [spatie/opening-hours#96]
Hi Guys,
i'm getting the message error "TimeRange array definition must at least contains an "hours" property.". It happend when I tried to execute the create method.on array below. 
$openingHours = OpeningHours::create($array_hours);

I realized that error i raised on "sunday" dayweek in the code snippet in vendor\spatie\opening-hours\src\Exceptions\InvalidTimeRangeArray.php at line 9  

Rules
On sundays i don't have any opening hours, in other words, there is no work on that day. So think that the "hours" property value must be blank. Look below. 
Is not this right way to represent this rule ?

array:8 [▼
  "exceptions" => array:1 [▶]
  "friday" => array:2 [▶]
  "monday" => array:2 [▶]
  "saturday" => array:3 [▶]
  "sunday" => array:1 [▼
    0 => array:2 [▼
      "hours" => ""
      "data" => ""
    ]
  ]
  "thursday" => array:2 [▼
    0 => array:2 [▼
      "hours" => "09:00-12:00"
      "data" => ""
    ]
    1 => array:2 [▶]
  ]
  "tuesday" => array:2 [▶]
  "wednesday" => array:1 [▶]
]
Thanks any suggestion.

**Comment by kylekatarnls** [comment]
Hello,

The empty string is not valid, you must pass an empty array: `"hours" => []` but if data and hours are both empty, you can completely remove the sunday property or use `"sunday" => []`

**Comment by gilsondelrei** [comment]
Hi Kyle,
for the sake of understanding i want to keep  the "sunday" in array. Following  your suggestion i tried pass an empty array but the message error is the same.

array:2 [▼
  "hours" => []
  "data" => ""
]

any suggestion ?

**Comment by kylekatarnls** [comment]
Please give us a complete code example (please use markdown ` ```php ` above ` ``` ` below) so we can reproduce your error by running this code.

**Comment by kylekatarnls** [comment]
The following code works perfectly on the last version:
```php
$openingHours = Spatie\OpeningHours\OpeningHours::create([
    'sunday' => [
        'hours' => [],
        'data' => '',
    ],
]);
```

**Comment by kylekatarnls** [comment]
I guess, you try to do this:
```php
$openingHours = Spatie\OpeningHours\OpeningHours::create([
    'sunday' => [
        [
            'hours' => [],
            'data' => '',
        ],
    ],
]);
```
This is not valid and mostly if you want an understanding data representation.

By creating 1 sub-array inside Sunday, you say, there is 1 range of time, but you don't define this range, if there is 0 ranges in Sunday, there is no reason to create any sub-array.

Using this syntax, you have as many sub-arrays as ranges in the day, so having 1 sub-array for a full-closed day does not make sense.
